from dataclasses import dataclass


@dataclass
class QBERType:
    RANDOM = 'random'
    BURSTY = 'bursty'

PATH_TO_RESULTS = '../results/raw/'
PATH_TO_PREPARED_RESULTS = '../results/prepared_new/'
RAW_TRAINING_DATASET_PATH = PATH_TO_RESULTS + 'whole_results_10_140.csv'
RAW_TESTING_DATASET_PATH = PATH_TO_RESULTS + 'whole_results_test_5_135.csv'

PREPARED_DATA_FILENAME = 'prepared_data'
STATS_DATA_FILENAME = 'stats'
RANDOM_QBER_DATA_PATH = PATH_TO_PREPARED_RESULTS + PREPARED_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_DATA_PATH = PATH_TO_PREPARED_RESULTS + PREPARED_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'
RANDOM_QBER_TEST_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + PREPARED_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_TEST_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + PREPARED_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'

RANDOM_QBER_STATS_DATA_PATH = PATH_TO_PREPARED_RESULTS + STATS_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_STATS_DATA_PATH = PATH_TO_PREPARED_RESULTS + STATS_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'
RANDOM_QBER_TEST_STATS_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + STATS_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_TEST_STATS_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + STATS_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'


PREPARED_DATA_HEADER = ['L','N', 'K', 'QBER','TAU_MISSES', 'REPETITIONS']
STATS_DATA_HEADER = ['L','N','K','QBER', 'MEAN_TAU_MISSES', 'MAX_REPS','MIN_REPS','MEAN_REPS','MEDIAN_REPS','STD_DEV','VAR']
