from dataclasses import dataclass


@dataclass
class QBERType:
    RANDOM = 'random'
    BURSTY = 'bursty'

PATH_TO_RESULTS = '../results/raw/'
PATH_TO_PREPARED_RESULTS = '../results/prepared/'
RAW_TRAINING_DATASET_PATH = PATH_TO_RESULTS + 'whole_results_10_140.csv'
RAW_TESTING_DATASET_PATH = PATH_TO_RESULTS + 'whole_results_test_5_135.csv'

PREPARED_DATA_FILENAME = 'prepared_data'
RANDOM_QBER_DATA_PATH = PATH_TO_PREPARED_RESULTS + PREPARED_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_DATA_PATH = PATH_TO_PREPARED_RESULTS + PREPARED_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'
RANDOM_QBER_TEST_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + PREPARED_DATA_FILENAME + '_' + QBERType.RANDOM + '.csv'
BURSTY_QBER_TEST_DATA_PATH = PATH_TO_PREPARED_RESULTS + 'test_' + PREPARED_DATA_FILENAME + '_' + QBERType.BURSTY + '.csv'
PREPARED_DATA_HEADER = ['L;N;K;QBER;REPETITIONS']
